apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev


patches:
- path: deployment-dev.yaml
- path: service-dev.yaml 
- path: hpa-dev.yaml 


configMapGenerator:
- name: mykustom-map
  env: config.properties
  behavior: merge