apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: prod


patches:
- path: deployment-prod.yaml
- path: service-prod.yaml 
- path: hpa-prod.yaml 

configMapGenerator:
- name: mykustom-map
  env: config.properties
  behavior: merge