apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: mywebapp
        image: nginx
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mywebapp-configmapv1.0